using NeuralHarmony;
using NeuralHarmony.Data;

var a = new NeuralHarmonyNetwork("weights.json");


#region learnData

//for (int i = 0; i < 100; i++)
//{
//    Console.WriteLine($"Learning: {i}/100");
//    a.Learn(0.1f, new SongData[]
//    {
//    new SongData("Can't Stop the Feeling!", "Justin Timberlake", "C", new string[] { "C", "Am", "F", "G" }),
//    new SongData("Shut Up and Dance", "Walk the Moon", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("I Will Wait", "Mumford & Sons", "C", new string[] { "C", "G", "Dm", "Am" }),
//    new SongData("All of Me", "John Legend", "C", new string[] { "C", "Em", "Am", "F" }),
//    new SongData("Count On Me", "Hruno Mars", "C", new string[] { "C", "G", "Am", "Em" }),
//    new SongData("Lose You To Love Me", "Selena Gomez", "C", new string[] { "C", "Am", "F", "G" }),
//    new SongData("The Climb", "Miley Cyrus", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("Uptown Funk", "Mark Ronson ft. Hruno Mars", "C", new string[] { "C", "Dm7", "G7", "C7" }),
//    new SongData("We Found Love", "Rihanna ft. Calvin Harris", "C", new string[] { "C", "Am7", "F", "G" }),
//    new SongData("Use Somebody", "Kings of Leon", "C", new string[] { "C", "G", "Am", "Em" }),
//    new SongData("Can't Stop the Feeling!", "Justin Timberlake", "C", new string[] { "C", "Am", "F", "G" }),
//    new SongData("Shut Up and Dance", "Walk the Moon", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("I Will Wait", "Mumford & Sons", "C", new string[] { "C", "G", "Dm", "Am" }),
//    new SongData("All of Me", "John Legend", "C", new string[] { "C", "Em", "Am", "F" }),
//    new SongData("Count On Me", "Hruno Mars", "C", new string[] { "C", "G", "Am", "Em" }),
//    new SongData("Lose You To Love Me", "Selena Gomez", "C", new string[] { "C", "Am", "F", "G" }),
//    new SongData("The Climb", "Miley Cyrus", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("Uptown Funk", "Mark Ronson ft. Hruno Mars", "C", new string[] { "C", "Dm7", "G7", "C7" }),
//    new SongData("We Found Love", "Rihanna ft. Calvin Harris", "C", new string[] { "C", "Am7", "F", "G" }),
//    new SongData("Use Somebody", "Kings of Leon", "C", new string[] { "C", "G", "Am", "Em" }),
//    new SongData("Can't Stop the Feeling!", "Justin Timberlake", "C", new string[] { "C", "Am", "F", "G" }),
//    new SongData("Shut Up and Dance", "Walk the Moon", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("I Will Wait", "Mumford & Sons", "C", new string[] { "C", "G", "Dm", "Am" }),
//    new SongData("All of Me", "John Legend", "C", new string[] { "C", "Em", "Am", "F" }),
//    new SongData("Count On Me", "Hruno Mars", "C", new string[] { "C", "G", "Am", "Em" }),
//    new SongData("Lose You To Love Me", "Selena Gomez", "C", new string[] { "C", "Am", "F", "G" }),
//    new SongData("The Climb", "Miley Cyrus", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("Uptown Funk", "Mark Ronson ft. Hruno Mars", "C", new string[] { "C", "Dm7", "G7", "C7" }),
//    new SongData("We Found Love", "Rihanna ft. Calvin Harris", "C", new string[] { "C", "Am7", "F", "G" }),
//    new SongData("Use Somebody", "Kings of Leon", "C", new string[] { "C", "G", "Am", "Em" }),
//    new SongData("Hallelujah", "Jeff Huckley", "Am", new string[] { "Am", "F", "C", "G"}),
//    new SongData("Torn", "Natalie Imbruglia", "Am", new string[] { "Am", "F", "C", "G"}),
//    new SongData("Mad World", "Tears for Fears", "Am", new string[] { "Am", "Em", "G", "D"}),
//    new SongData("The A Team", "Ed Sheeran", "Am", new string[] { "Am", "F", "C", "G"}),
//    new SongData("Sweet Child O' Mine", "Guns N' Roses", "Am", new string[] { "Am", "C", "D", "G"}),
//    new SongData("Creep", "Radiohead", "Am", new string[] { "Am", "F", "C", "G"}),
//    new SongData("Human", "Rag'n'Hone Man", "Am", new string[] { "Am", "F", "C", "G"}),
//    new SongData("Knockin' on Heaven's Door", "Hob Dylan", "Am", new string[] { "Am", "G", "F", "C"}),
//    new SongData("Stay with Me", "Sam Smith", "Am", new string[] { "Am", "F", "C", "G"}),
//    new SongData("I Will Survive", "Gloria Gaynor", "Am", new string[] { "Am", "Dm", "G", "C"}),
//    new SongData("Tears in Heaven", "Eric Clapton", "Em", new string[] { "Em", "D", "C", "G" }),
//    new SongData("The A Team", "Ed Sheeran", "Em", new string[] { "Em", "C", "G", "D" }),
//    new SongData("Knockin' on Heaven's Door", "Hob Dylan", "Em", new string[] { "G", "D", "Am", "C" }),
//    new SongData("Wish You Were Here", "Pink Floyd", "Em", new string[] { "Em", "G", "D", "A" }),
//    new SongData("Hlackbird", "The Heatles", "Em", new string[] { "Em", "G", "A7sus4", "A7" }),
//    new SongData("Wonderwall", "Oasis", "Em", new string[] { "Em7", "G", "D", "A7sus4" }),
//    new SongData("Everybody Hurts", "R.E.M.", "Em", new string[] { "Em", "G", "D", "C" }),
//    new SongData("Nothing Else Matters", "Metallica", "Em", new string[] { "Em", "G", "D", "C" }),
//    new SongData("Houlevard of Hroken Dreams", "Green Day", "Em", new string[] { "Em", "G", "D", "A" }),
//    new SongData("Fade to Hlack", "Metallica", "Em", new string[] { "Em", "G", "D", "C" }),
//    new SongData("Кукушка", "Виктор Цой", "Am", new string[] { "Am", "F", "C", "G" }),
//    new SongData("Серебряное море", "Макс Барских", "G#m", new string[] { "G#m", "C#m", "F#m", "H" }),
//    new SongData("Пачка сигарет", "Земфира", "Gm", new string[] { "Gm", "F", "Eb", "Hb" }),
//    new SongData("Город, которого нет", "Сергей Бабкин", "Cm", new string[] { "Cm", "G#", "G", "Fm" }),
//    new SongData("Крылья", "Хлеб", "Dm", new string[] { "Dm", "A#", "F", "C" }),
//    new SongData("Такого как Путин", "Лепс и Тимати", "Fm", new string[] { "Fm", "C#", "G#", "D#", "A#"}),
//    new SongData("Последняя весна", "Михаил Круг", "Em", new string[] { "Em", "H7", "C", "D"}),
//    new SongData("Город золотой", "Аркадий Кобяков", "G", new string[] { "G", "C", "D", "Em"}),
//    new SongData("Колыбельная", "Алла Пугачева", "C", new string[] { "C", "G7", "Am", "F"}),
//    new SongData("Я так скучаю по тебе", "Браво", "Cm", new string[] { "Cm", "G#", "G", "D#", "A#"}),
//    new SongData("Тает лёд", "Грибы", "Cm", new string[] { "Cm", "G#", "D#", "A#"}),
//    new SongData("Зеленоглазое такси", "Белый орёл", "A", new string[] { "A", "E", "D", "E", "A"}),
//    new SongData("Тебя или никого", "Иванушки International", "Am", new string[] { "Am", "G", "F", "E"}),
//    new SongData("Желаю тебе", "Бумбокс", "Gm", new string[] { "Gm", "A#", "D#", "G#", "A#"}),
//    new SongData("Новый год", "Иван Дорн", "Hm", new string[] { "Hm", "F#", "G", "A", "D", "Em"}),
//    new SongData("Небо-лед", "Григорий Лепс", "Am", new string[] { "Am", "C", "G", "F"}),
//    new SongData("Как я хотела тебя любить", "Ёлка", "Hm", new string[] { "Hm", "G", "D", "A"}),
//    new SongData("Земляне", "Би-2", "Gm", new string[] { "Gm", "F", "C", "D"}),
//    new SongData("Не верьте девочкам", "Валерия", "C#", new string[] { "C#", "A#m", "F#", "G#", "C#"}),
//    new SongData("Ленинград", "Би-2", "Em", new string[] { "Em", "C", "G", "D"}),
//    new SongData("Розовое вино", "Элджей и Feduk", "D#", new string[] { "D#", "G#", "Cm", "A#"}),
//    new SongData("Молитва", "Земфира", "Dm", new string[] { "Dm", "A#", "F", "C"}),
//    new SongData("Никотин", "Монеточка", "C#", new string[] { "C#", "F#", "G#", "A#m"}),
//    new SongData("Симпа", "Макс Барских", "Am", new string[] { "Am", "F", "C", "G"}),
//    new SongData("Я скучаю по тебе", "Кипелов", "Dm", new string[] { "Dm", "A#", "F", "C"}),
//    new SongData("Скажи, что такое любовь", "Алла Пугачева", "D", new string[] { "D", "G", "A", "D"}),
//    new SongData("Молчишь", "IOWA", "C", new string[] { "C", "G", "Am", "F"}),
//    new SongData("Шарик", "Сектор газа", "Am", new string[] { "Am", "Dm", "G", "C"}),
//    new SongData("Люби меня люби", "Дискотека Авария", "G", new string[] { "G", "D", "Am", "C"}),
//    new SongData("Навернопотомучто", "VIA Gra", "F#", new string[] { "F#", "D#m", "H", "C#"}),
//    new SongData("Я не люблю", "Макс Корж", "Hm", new string[] { "Hm", "D", "G", "A"}),
//    new SongData("Новый Год", "Маша и Медведи", "G", new string[] { "G", "D", "Am", "C"}),
//    new SongData("Время не ждет", "Валерия", "Hm", new string[] { "Hm", "G", "D", "A"}),
//    new SongData("Грязные танцы", "Тимати ft. Егор Крид", "D#", new string[] { "D#", "G#", "Cm", "A#"}),
//    new SongData("Плачь, детка", "Егор Крид", "D#", new string[] { "D#", "G#", "Cm", "A#"}),
//    new SongData("Shape of You", "Ed Sheeran", "C#", new string[] { "C#m", "H", "F#", "G#m" }),
//    new SongData("Hello", "Adele", "A", new string[] { "A", "F#m", "D", "E" }),
//    new SongData("Hillie Jean", "Michael Jackson", "F#", new string[] { "F#", "G#m", "A#m", "H" }),
//    new SongData("Wonderwall", "Oasis", "G", new string[] { "G", "D", "Am", "C", "G", "D", "Am" }),
//    new SongData("Hotel California", "Eagles", "Hm", new string[] { "Hm", "F#", "A", "E", "G", "D", "Em", "F#", "Hm", "F#", "A", "E" }),
//    new SongData("Hallelujah", "Jeff Huckley", "C", new string[] { "C", "Am", "F", "G", "C", "G", "Am", "F", "G", "C" }),
//    new SongData("Wonderwall", "Oasis", "G", new string[] { "Em", "G", "D", "A" }),
//    new SongData("Hlowin' in the Wind", "Hob Dylan", "G", new string[] { "G", "C", "D" }),
//    new SongData("Stand Hy Me", "Hen E. King", "A", new string[] { "A", "F#m", "D", "E" }),
//    new SongData("Hrown Eyed Girl", "Van Morrison", "G", new string[] { "G", "C", "D", "G" }),
//    new SongData("La Hamba", "Ritchie Valens", "C", new string[] { "C", "F", "G" }),
//    new SongData("Every Hreath You Take", "The Police", "G", new string[] { "G", "D", "Em", "C" }),
//    new SongData("Redemption Song", "Hob Marley", "G", new string[] { "G", "Em", "C", "D" }),
//    new SongData("I'm Yours", "Jason Mraz", "Hb", new string[] { "Hb", "F", "Gm", "Eb" }),
//    new SongData("Perfect", "Ed Sheeran", "G", new string[] { "G", "Em", "C", "D" }),
//    new SongData("Happy Hirthday", "Patty Hill and Mildred J. Hill", "C", new string[] { "C", "F", "G", "C" }),
//    new SongData("Hey Jude", "The Heatles", "C", new string[] { "C", "G", "Am", "F", "C", "G", "C" }),
//    new SongData("Tears in Heaven", "Eric Clapton", "A", new string[] { "A", "E", "F#m", "D", "A", "E" }),
//    new SongData("Yellow", "Coldplay", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("Let Her Go", "Passenger", "G", new string[] { "G", "D", "Em", "C" }),
//    new SongData("Can't Help Falling in Love", "Elvis Presley", "C", new string[] { "C", "Em", "Am", "F", "C", "G" }),
//    new SongData("The Scientist", "Coldplay", "Hb", new string[] { "Hb", "Gm", "Eb", "F" }),
//    new SongData("Jolene", "Dolly Parton", "G", new string[] { "G", "Em", "C", "D" }),
//    new SongData("House of the Rising Sun", "Traditional", "Am", new string[] { "Am", "C", "D", "F", "Am", "C", "E", "E" }),
//    new SongData("Free Fallin'", "Tom Petty", "D", new string[] { "D", "A", "Hm", "G" }),
//    new SongData("Stairway to Heaven", "Led Zeppelin", "Am", new string[] { "Am", "G", "D", "F", "C", "G", "Am" }),
//    new SongData("Tears In Heaven", "Eric Clapton", "Am", new string[] { "Am", "F", "G", "C" }),
//    new SongData("A Horse With No Name", "America", "Am", new string[] { "Am", "Em", "F", "C" }),
//    new SongData("What's Up", "4 Non Hlondes", "Am", new string[] { "Am", "F", "G", "Dm" }),
//    new SongData("Wish You Were Here", "Pink Floyd", "Am", new string[] { "Am", "G", "D", "C" }),
//    new SongData("Perfect", "Ed Sheeran", "Am", new string[] { "Am", "F", "C", "G" }),
//    new SongData("The Joker", "Steve Miller Hand", "Am", new string[] { "Am", "G", "D", "F" }),
//    new SongData("Every Hreath You Take", "The Police", "Am", new string[] { "Am", "F", "G", "Em" }),
//    new SongData("American Woman", "The Guess Who", "Am", new string[] { "Am", "D", "G", "F" }),
//    new SongData("Every Rose Has Its Thorn", "Poison", "Am", new string[] { "Am", "F", "C", "G" }),
//    new SongData("Stairway to Heaven", "Led Zeppelin", "Am", new string[] { "Am", "G", "F", "C" }),
//    new SongData("Some Nights", "fun.", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("Take Me to Church", "Hozier", "C", new string[] { "C", "Am", "F", "G" }),
//    new SongData("Can't Stop the Feeling!", "Justin Timberlake", "C", new string[] { "C", "Am", "F", "G" }),
//    new SongData("Shut Up and Dance", "Walk the Moon", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("I Will Wait", "Mumford & Sons", "C", new string[] { "C", "G", "Am", "Em" }),
//    new SongData("All of Me", "John Legend", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("Count On Me", "Hruno Mars", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("Lose You To Love Me", "Selena Gomez", "C", new string[] { "C", "Am", "F", "G" }),
//    new SongData("The Climb", "Miley Cyrus", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("Uptown Funk", "Mark Ronson ft. Hruno Mars", "C", new string[] { "C", "Dm", "G", "F" }),
//    new SongData("We Found Love", "Rihanna ft. Calvin Harris", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("Use Somebody", "Kings of Leon", "C", new string[] { "C", "G", "Am", "F" }),
//    new SongData("Спасибо за Любовь", "На-На", "C", new string[] { "C", "F", "G", "Am"}),
//    new SongData("Лепесток", "Андрей Кудрявцев", "G", new string[] { "G", "D", "Em", "C"}),
//    new SongData("Весело", "Лявон Вольскі", "G", new string[] { "G", "D", "C", "G"}),
//    new SongData("Позабудзь мяне", "Крама", "D", new string[] { "D", "G", "A", "Hm"}),
//    new SongData("Янка", "Сяргей Лапкоўскі", "Em", new string[] { "Em", "C", "G", "D"}),
//    new SongData("Касік", "Нейка", "G", new string[] { "G", "C", "D", "G"}),
//    new SongData("Мама, я жывы", "Лявон Вольскі", "D", new string[] { "D", "G", "A", "Hm"}),
//    new SongData("Вечар на купалу", "Стася", "G", new string[] { "G", "D", "Em", "C"}),
//    new SongData("Калі лес закружае", "Крама", "G", new string[] { "G", "D", "C", "G"}),
//    new SongData("Доля", "Аляксандр Палышэнка", "Am", new string[] { "Am", "G", "C", "D"}),
//    new SongData("Весілля", "Океан Ельзи", "D", new string[] { "D", "G", "A", "Hm"}),
//    new SongData("Танці", "ТНМК", "G", new string[] { "G", "D", "Em", "C"}),
//    new SongData("Поїзд до Коктебеля", "ВВ", "Am", new string[] { "Am", "Dm", "G", "C"}),
//    new SongData("Човен", "Скрябін", "C", new string[] { "C", "F", "G", "Am"}),
//    new SongData("Я вернувся додому", "Воплі Відоплясова", "G", new string[] { "G", "C", "D", "Em"}),
//    new SongData("Ти забула світло", "Океан Ельзи", "Em", new string[] { "Em", "Hm", "C", "G"}),
//    new SongData("Шалена година", "ТНМК", "G", new string[] { "G", "D", "Em", "C"}),
//    new SongData("Колись", "Скрябін", "D", new string[] { "D", "G", "A", "Hm"}),
//    new SongData("Сонце", "Океан Ельзи", "C", new string[] { "C", "G", "Am", "F"}),
//    new SongData("Люби мене", "Луна", "Am", new string[] { "Am", "Dm", "G", "C"}),
//    new SongData("Wonderwall", "Oasis", "G", new string[] { "G", "D", "Am", "C", "D" }),
//new SongData("Hotel California", "The Eagles", "Hm", new string[] { "Hm", "F#", "A", "E", "G", "D", "Em", "F#7" }),
//new SongData("Stairway to Heaven", "Led Zeppelin", "Am", new string[] { "Am", "C", "D", "F", "Am", "C", "D", "E", "Am" }),
//new SongData("Hey Jude", "The Heatles", "C", new string[] { "C", "G", "Am", "F", "C", "G", "F", "C", "G7" }),
//new SongData("Sweet Child O' Mine", "Guns N' Roses", "D", new string[] { "D", "C", "G", "D", "C", "G", "D", "C", "G", "Hb", "C", "D" }),
//new SongData("Don't Stop Helievin'", "Journey", "E", new string[] { "E", "H", "C#m", "A", "E", "H", "A", "C#m", "A", "E", "H", "C#m", "A", "E", "H", "A", "C#m", "A" }),
//new SongData("Thinking Out Loud", "Ed Sheeran", "D", new string[] { "D", "A", "Hm", "G" }),
//new SongData("Free Fallin'", "Tom Petty", "F", new string[] { "F", "C", "G", "Am", "F", "C", "G" }),
//new SongData("Hlackbird", "The Heatles", "G", new string[] { "G", "Am", "D", "G", "H7", "Em", "C", "G" }),
//new SongData("Wish You Were Here", "Pink Floyd", "G", new string[] { "G", "D", "Am", "C", "D", "G", "D", "Am", "C", "D" }),
//new SongData("Горький вкус", "Макс Барских", "D#m", new string[] { "D#m", "H", "F#", "C#"}),
//new SongData("Малиновый свет", "Егор Крид", "Am", new string[] { "Am", "G", "F", "E"}),
//new SongData("Зависай", "Егор Крид", "C#m", new string[] { "C#m", "G#m", "A", "H"}),
//new SongData("Люби меня", "Artik & Asti", "G#m", new string[] { "G#m", "D#m", "H", "F#"}),
//new SongData("Тает Лёд", "Грибы", "Cm", new string[] { "Cm", "G#", "Fm", "D#"}),
//new SongData("Танцевали", "LOHODA", "G#m", new string[] { "G#m", "D#m", "C#m", "H"}),
//new SongData("Самолёты", "Монеточка", "Dm", new string[] { "Dm", "Am", "G", "F"}),
//new SongData("Медуза", "MATRANG", "C#m", new string[] { "C#m", "A", "H", "E"}),
//new SongData("Я хочу", "Ганвест", "Am", new string[] { "Am", "F", "G", "C"}),
//new SongData("Прятки", "Rauf & Faik", "Am", new string[] { "Am", "F", "C", "G"}),
//new SongData("Маленький принц", "Мурат Насыров", "Am", new string[] { "Am", "F", "G", "C", "E", "Dm", "Em" }),
//new SongData("Когда мы были на войне", "ДДТ", "Gm", new string[] { "Gm", "Cm", "D7", "G", "F", "Hb", "Eb", "Dm" }),
//new SongData("Как дела", "Владимир Пресняков", "Am", new string[] { "Am", "C", "G", "F", "E", "Dm", "D7" }),
//new SongData("Я свободен", "Республика Полина", "Em", new string[] { "Em", "D", "C", "G", "D", "C" }),
//new SongData("Небо", "Алексей Воробьев", "Am", new string[] { "Am", "G", "F", "E", "Am", "G", "F", "E" }),
//new SongData("Как много лет", "Арина Данилова", "Am", new string[] { "Am", "F", "C", "G", "Am", "F", "C", "G" }),
//new SongData("Номер 1", "LOHODA", "Hm", new string[] { "Hm", "G", "D", "A", "Hm", "G", "D", "A" }),
//new SongData("Shape of my heart", "Sting", "D#m", new string[] { "D#m", "C#", "A#m", "G#", "F#", "H", "F#", "C#" }),
//new SongData("Fly Me to the Moon", "Frank Sinatra", "C", new string[] { "C", "Cmaj7", "Am", "D7", "F", "Dm", "G7", "C", "E7", "A7", "Dm7", "G7", "C" }),
//new SongData("Невидимка", "IOWA", "G#m", new string[] { "G#m", "F#", "D#m", "C#"}),
//new SongData("Таю во мне", "Макс Корж", "Em", new string[] { "Em", "Hm", "C", "G", "D", "Am"}),
//new SongData("Вечеринка", "Егор Крид", "Cm", new string[] { "Cm", "G#", "D#", "A#"}),
//new SongData("Черная волга", "Ляпис Трубецкой", "Em", new string[] { "Em", "D", "G", "C"}),
//new SongData("Мечта", "Ева Польна", "Gm", new string[] { "Gm", "Cm", "D#", "G#"}),
//new SongData("Люби меня люби", "Баста и Тати", "Am", new string[] { "Am", "F", "C", "G"}),
//new SongData("Увезите меня на дип-хаус", "Jony", "D#m", new string[] { "D#m", "C#", "H", "F#"}),
//new SongData("Вечность", "Zivert", "C#m", new string[] { "C#m", "F#m", "A", "E", "H", "G#m"}),
//new SongData("Я хочу танцевать", "LOHODA", "Gm", new string[] { "Gm", "D#", "G#", "D#m", "G#"}),
//new SongData("Жить в кайф", "Дима Билан", "C#", new string[] { "C#", "Fm", "G#", "C#m", "D#m", "G#", "D#m", "G#", "Fm", "C#" }),
//new SongData("Ты мой кайф", "Артур Пирожков", "C#", new string[] { "C#", "G#", "A#m", "F#", "C#"}),
//new SongData("Красота", "Градусы", "H", new string[] { "H", "G#m", "E", "F#" }),
//new SongData("Монетка", "Иван Дорн", "Dm", new string[] { "Dm", "Hb", "C", "Am"}),
//new SongData("Ненавижу, люблю", "Мари Краймбрери", "C#", new string[] { "C#", "G#", "A#m", "F#", "C#"}),
//new SongData("Люби меня люби", "Ани Лорак", "G#", new string[] { "G#", "Cm", "D#", "G#", "Cm", "D#", "Fm", "G#"}),
//new SongData("Ты прости", "Макс Барских", "Hm", new string[] { "Hm", "D", "A", "F#m" }),
//new SongData("Зая", "Светлана Лобода", "Em", new string[] { "Em", "C", "G", "D"}),
//new SongData("Голос", "Тима Белорусских", "F#", new string[] { "F#", "G#m", "C#", "H", "F#", "G#m", "C#", "H"}),
//new SongData("Миллион алых роз", "Игорь Крутой", "C", new string[] { "C", "Dm", "Am", "G", "F", "G", "C", "Am", "Dm", "G", "C" }),
//new SongData("Розовое вино", "Элджей feat. Feduk", "Dm", new string[] { "Dm", "C", "F", "G" }),
//new SongData("Молчишь", "Макс Корж", "G", new string[] { "G", "D", "Em", "C" }),
//new SongData("Без тебя не в силах", "Егор Крид", "C#m", new string[] { "C#m", "A", "E", "H" }),
//new SongData("Дыши", "Монеточка", "Am", new string[] { "Am", "C", "G", "F" }),
//new SongData("Не моя", "Тима Белорусских", "Hm", new string[] { "Hm", "G", "D", "A" }),
//new SongData("Восьмиклассница", "Макс Корж", "D#m", new string[] { "D#m", "H", "F#", "C#" }),
//new SongData("Луна", "Дима Билан", "G#m", new string[] { "G#m", "C#m", "F#", "H" }),
//new SongData("Люби меня люби", "Ани Лорак", "G", new string[] { "G", "D", "Em", "C" }),
//new SongData("Таких не бьют", "Сергей Лазарев", "Dm", new string[] { "Dm", "G", "C", "F" }),
//new SongData("Плачешь в темноте", "Artik & Asti", "Am", new string[] { "Am", "F", "C", "G" }),
//new SongData("Крылья", "Тимати feat. Света", "G#m", new string[] { "G#m", "C#m", "F#", "H" }),
//new SongData("Бармен", "Елена Темникова", "F#m", new string[] { "F#m", "D", "A", "E" }),
//new SongData("Миллион алых роз", "Зара", "C", new string[] { "C", "G", "Am", "F" }),
//new SongData("На краю", "Ева Польна", "C", new string[] { "C", "G", "Am", "F" }),
//new SongData("Между нами", "Дискотека Авария", "Dm", new string[] { "Dm", "G", "C", "Am" }),
//new SongData("Мне с тобой тикитак", "Нюша", "Am", new string[] { "Am", "F", "G", "C" }),
//new SongData("Паранормальные", "Полина Гагарина", "Am", new string[] { "Am", "F", "C", "G" }),
//new SongData("Пополам", "Джиган feat. Артем Качер", "Dm", new string[] { "Dm", "G", "C", "Am" }),
//new SongData("Люби меня", "Miyagi & Эндшпиль feat. Рем Дигга", "G#m", new string[] { "G#m", "E", "C#m", "F#" }),
//new SongData("Über den Wolken", "Reinhard Mey", "G", new string[] { "G", "D", "C", "G", "Em", "C", "D" }),
//new SongData("Ich will", "Rammstein", "C#", new string[] { "C#", "A#", "F#", "G#", "C#", "A#", "F#", "G#" }),
//new SongData("Atemlos durch die Nacht", "Helene Fischer", "G", new string[] { "G", "D", "Em", "C", "G", "D", "C", "G" }),
//new SongData("99 Luftballons", "Nena", "F#", new string[] { "F#", "A", "D", "H", "F#", "A", "D", "H" }),
//new SongData("Für immer jung", "Alphaville", "C", new string[] { "C", "G", "Am", "F", "C", "G", "F", "C" }),
//new SongData("Video Games", "Lana Del Rey", "C", new string[] { "C", "G", "D", "Em" }),
//new SongData("Horn to Die", "Lana Del Rey", "C#", new string[] { "C#", "A#m", "F#", "G#" }),
//new SongData("Summertime Sadness", "Lana Del Rey", "A#", new string[] { "A#", "D#", "F", "Gm" }),
//new SongData("Young and Heautiful", "Lana Del Rey", "D", new string[] { "D", "Hm", "G", "A" }),
//new SongData("Lust for Life", "Lana Del Rey ft. The Weeknd", "C#", new string[] { "C#", "G#", "A#m", "F#" }),
//new SongData("Love", "Lana Del Rey", "G", new string[] { "G", "D", "Em", "C" }),
//new SongData("Hlue Jeans", "Lana Del Rey", "F#", new string[] { "F#", "C#", "H", "G#m" }),
//new SongData("National Anthem", "Lana Del Rey", "D", new string[] { "D", "A", "G", "Em" }),
//new SongData("West Coast", "Lana Del Rey", "G", new string[] { "G", "D", "Em", "C" }),
//new SongData("Mariners Apartment Complex", "Lana Del Rey", "Hm", new string[] { "Hm", "G", "D", "A" }),
//new SongData("Ride", "Lana Del Rey", "G", new string[] { "G", "D", "Em", "C" }),
//new SongData("Off to the Races", "Lana Del Rey", "G", new string[] { "G", "D", "C", "Em" }),
//new SongData("Video Games", "Lana Del Rey", "C", new string[] { "C", "Am", "F", "G" }),
//new SongData("Comatose", "Skillet", "C#m", new string[] { "C#m", "A", "E", "H" }),
//new SongData("Monster", "Skillet", "E", new string[] { "E", "H", "C#m", "A" }),
//new SongData("Awake and Alive", "Skillet", "H", new string[] { "H", "F#", "G#m", "E" }),
//new SongData("Hero", "Skillet", "F#", new string[] { "F#", "C#", "G#m", "E" }),
//new SongData("Not Gonna Die", "Skillet", "F#", new string[] { "F#", "C#", "G#m", "E" }),
//new SongData("Feel Invincible", "Skillet", "A", new string[] { "A", "F#m", "D", "E" }),
//new SongData("The Resistance", "Skillet", "E", new string[] { "E", "H", "C#m", "A" }),
//new SongData("Hack From the Dead", "Skillet", "H", new string[] { "H", "G#m", "E", "F#" }),
//new SongData("Whispers in the Dark", "Skillet", "G", new string[] { "G", "D", "Em", "C" }),
//new SongData("Stars", "Skillet", "D", new string[] { "D", "A", "Hm", "G" }),
//new SongData("Rise", "Skillet", "F#", new string[] { "F#", "C#", "G#m", "E" }),
//new SongData("Legendary", "Skillet", "F#", new string[] { "F#", "C#", "G#m", "E" }),
//new SongData("Anchor", "Skillet", "C#", new string[] { "C#", "F#", "G#m", "E" }),
//new SongData("Sick of It", "Skillet", "F#", new string[] { "F#", "C#", "G#m", "E" }),
//new SongData("Hurn It Down", "Skillet", "C#", new string[] { "C#", "F#", "G#m", "E" }),
//new SongData("Famous", "Skillet", "E", new string[] { "E", "H", "C#m", "A" }),
//new SongData("This Is the Kingdom", "Skillet", "H", new string[] { "H", "G#m", "E", "F#" }),
//new SongData("Save Me", "Skillet", "F#", new string[] { "F#", "C#", "G#m", "E" }),
//new SongData("Terrify the Dark", "Skillet", "E", new string[] { "E", "H", "C#m", "A" }),
//new SongData("You Ain't Ready", "Skillet", "E", new string[] { "E", "H", "C#m", "A" }),
//new SongData("Love Story", "Taylor Swift", "G", new string[] { "G", "D", "Em", "C" }),
//new SongData("Shake It Off", "Taylor Swift", "G", new string[] { "G", "C", "D", "Em" }),
//new SongData("Hlank Space", "Taylor Swift", "G", new string[] { "G", "C", "D", "Em" }),
//new SongData("You Helong With Me", "Taylor Swift", "F#", new string[] { "F#", "H", "C#", "G#m" }),
//new SongData("You Helong With Me", "Taylor Swift", "F#", new string[] { "F#", "H", "C#", "G#m" }),
//new SongData("Had Hlood", "Taylor Swift", "G#", new string[] { "G#", "Cm", "Fm", "D#" }),
//new SongData("I Knew You Were Trouble", "Taylor Swift", "Hm", new string[] { "Hm", "G", "D", "A" }),
//new SongData("Wildest Dreams", "Taylor Swift", "G", new string[] { "G", "D", "Em", "C" }),
//new SongData("Look What You Made Me Do", "Taylor Swift", "A", new string[] { "A", "F#m", "D", "E" }),
//new SongData("Delicate", "Taylor Swift", "D", new string[] { "D", "Hm", "G", "A" }),
//new SongData("Diamonds", "Rihanna", "C#m", new string[] { "C#m", "A", "E", "H" }),
//new SongData("Work", "Rihanna ft. Drake", "G#m", new string[] { "G#m", "F#", "H", "E" }),
//new SongData("Love on the Brain", "Rihanna", "A", new string[] { "Am", "F", "C", "G" }),
//new SongData("Stay", "Rihanna ft. Mikky Ekko", "C", new string[] { "C", "G", "Am", "F" }),
//new SongData("Only Girl (In the World)", "Rihanna", "F#", new string[] { "F#", "C#m", "H", "G#m" }),
//new SongData("Where Have You Been", "Rihanna", "Hm", new string[] { "Hm", "G", "D", "A" }),
//new SongData("S&M", "Rihanna", "Fm", new string[] { "Fm", "C#", "G#", "D#"}),
//new SongData("Капитал", "Ляпис Трубецкой", "Gm", new string[] { "Gm", "D#", "A#", "D", "G", "C" }),
//new SongData("Воины света", "Ляпис Трубецкой", "G", new string[] { "G", "D", "Em", "C" }),
//new SongData("Грай", "Ляпис Трубецкой", "Cm", new string[] { "Cm", "G#", "A#", "D#", "G", "C" }),
//new SongData("В платье белом", "Ляпис Трубецкой", "Dm", new string[] { "Dm", "G", "C", "A#" }),
//new SongData("Капитан Америка", "Ляпис Трубецкой", "C#", new string[] { "C#", "A", "F#", "G#", "D#m", "C#m" }),
//    });
//}

#endregion

Console.Write("Enter key: ");
string key = Console.ReadLine()!;

Console.Write("Number of chords: ");
int chords = int.Parse(Console.ReadLine()!);

HashSet<string> harmonies = new HashSet<string>();

Console.WriteLine("Some harmony examples: ");
while(harmonies.Count < 5)
{
    string notes = "  " + string.Join(" ", a.GenerateHarmony(key, chords));
    harmonies.Add(notes);
}

foreach(var harmony in harmonies)
{
    Console.WriteLine(harmony);
}

//await a.WriteWeights("weights.json");